/*
 * Copyright Consensys Software Inc., 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package tech.pegasys.teku.reference;

import java.util.Set;
import tech.pegasys.teku.ethtests.finder.TestDefinition;
import tech.pegasys.teku.infrastructure.ssz.sos.SszMaxLengthExceededException;

/**
 * TEMPORARY. Teku enforces the consensus count limits of progressive lists (e.g. {@code
 * MAX_ATTESTATIONS_ELECTRA}) in the SSZ schemas, as consensus-specs PR 5564 allows. Reference test
 * fixtures that exceed such a limit are always ones expected to be invalid, but they fail at
 * deserialization with {@link SszMaxLengthExceededException} before the executor can assert the
 * rejection it was written for.
 *
 * <p>Those fixtures are listed here by display name, as printed in test reports. A listed fixture
 * passes when, and only when, it is rejected by an SSZ limit. To remove this once the fixtures
 * respect the limits: delete this class, its test, and the call in {@link Eth2ReferenceTestCase}.
 */
public class SszMaxLengthFixtures {

  public static final SszMaxLengthFixtures REJECTED_BY_SSZ_LIMITS =
      new SszMaxLengthFixtures(
          Set.of(
              "gloas - minimal - ssz_static/BeaconBlock - ssz_zero/case_0",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_17",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_28",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_10",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_26",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_19",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_21",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_5",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_2",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_20",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_27",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_18",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_11",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_16",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_29",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_3",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_4",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_8",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_1",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_6",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_13",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_14",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_22",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_25",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_7",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_0",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_9",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_24",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_23",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_15",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_lengthy/case_12",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_28",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_10",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_26",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_19",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_21",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_5",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_2",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_18",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_11",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_16",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_3",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_4",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_6",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_13",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_14",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_22",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_25",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_7",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_9",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_24",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_15",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random_chaos/case_12",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_17",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_28",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_10",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_26",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_19",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_21",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_5",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_2",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_20",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_27",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_18",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_11",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_16",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_29",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_3",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_4",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_8",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_1",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_6",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_13",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_14",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_22",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_25",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_7",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_0",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_9",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_24",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_23",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_15",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_one/case_12",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_max/case_0",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_17",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_28",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_10",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_26",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_19",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_21",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_5",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_2",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_20",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_27",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_18",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_11",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_16",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_29",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_3",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_4",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_8",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_1",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_6",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_13",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_14",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_25",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_7",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_0",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_9",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_24",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_23",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_15",
              "gloas - minimal - ssz_static/BeaconBlock - ssz_random/case_12",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_zero/case_0",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_17",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_28",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_10",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_26",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_19",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_21",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_5",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_2",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_20",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_27",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_18",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_11",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_16",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_29",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_3",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_4",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_8",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_1",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_6",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_13",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_14",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_22",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_25",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_7",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_0",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_9",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_24",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_23",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_15",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_lengthy/case_12",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_17",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_10",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_19",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_21",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_5",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_2",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_20",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_18",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_16",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_29",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_3",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_4",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_8",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_6",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_25",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_7",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_0",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_9",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_24",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_23",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_15",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random_chaos/case_12",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_17",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_28",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_10",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_26",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_19",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_21",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_5",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_2",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_20",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_27",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_18",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_11",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_16",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_29",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_3",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_4",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_8",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_1",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_6",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_13",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_14",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_22",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_25",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_7",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_0",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_9",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_24",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_23",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_15",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_one/case_12",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_28",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_26",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_19",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_21",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_5",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_2",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_20",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_27",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_18",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_11",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_16",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_29",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_3",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_4",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_8",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_1",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_6",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_13",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_14",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_22",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_25",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_7",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_0",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_9",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_24",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_15",
              "gloas - minimal - ssz_static/SignedBeaconBlock - ssz_random/case_12",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_zero/case_0",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_17",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_28",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_10",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_26",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_19",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_21",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_5",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_2",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_20",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_27",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_18",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_11",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_16",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_29",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_3",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_4",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_8",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_1",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_6",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_13",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_14",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_22",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_25",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_7",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_0",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_9",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_24",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_23",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_15",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_lengthy/case_12",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_28",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_10",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_26",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_19",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_5",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_2",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_20",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_27",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_11",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_16",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_29",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_3",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_4",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_8",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_6",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_14",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_22",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_25",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_7",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_9",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_24",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_23",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random_chaos/case_12",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_17",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_28",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_10",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_26",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_19",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_21",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_5",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_2",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_20",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_27",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_18",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_11",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_16",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_29",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_3",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_4",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_8",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_1",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_6",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_13",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_14",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_22",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_25",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_7",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_0",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_9",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_24",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_23",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_15",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_one/case_12",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_max/case_0",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_17",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_28",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_10",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_26",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_19",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_21",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_5",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_2",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_20",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_27",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_18",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_11",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_16",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_29",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_3",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_4",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_8",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_1",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_6",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_13",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_14",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_22",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_25",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_7",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_0",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_9",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_24",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_23",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_15",
              "gloas - minimal - ssz_static/BeaconBlockBody - ssz_random/case_12",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_contains_deposits",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_payload_attestations",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_proposer_slashings",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_parent_builder_exit_requests",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_parent_withdrawal_requests",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_bls_to_execution_changes",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_attester_slashings",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_parent_consolidation_requests",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_parent_builder_deposit_requests",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_voluntary_exits",
              "gloas - minimal - networking/gossip_beacon_block - gossip_beacon_block__reject_too_many_attestations",
              "gloas - minimal - networking/gossip_execution_payload_envelope - gossip_execution_payload_envelope__reject_too_many_builder_deposit_requests",
              "gloas - minimal - networking/gossip_execution_payload_envelope - gossip_execution_payload_envelope__reject_too_many_builder_exit_requests",
              "gloas - minimal - networking/gossip_execution_payload_envelope - gossip_execution_payload_envelope__reject_too_many_withdrawal_requests",
              "gloas - minimal - networking/gossip_execution_payload_envelope - gossip_execution_payload_envelope__reject_too_many_consolidation_requests",
              "gloas - minimal - networking/gossip_execution_payload_envelope - gossip_execution_payload_envelope__reject_too_many_withdrawals",
              "gloas - minimal - operations/attester_slashing - invalid_too_many_attesting_indices",
              "gloas - minimal - operations/parent_execution_payload - invalid_too_many_withdrawal_requests",
              "gloas - minimal - operations/parent_execution_payload - invalid_too_many_builder_deposit_requests",
              "gloas - minimal - operations/parent_execution_payload - invalid_too_many_consolidation_requests",
              "gloas - minimal - operations/parent_execution_payload - invalid_too_many_builder_exit_requests",
              "gloas - minimal - sanity/blocks - invalid_too_many_deposits",
              "gloas - minimal - sanity/blocks - invalid_too_many_proposer_slashings",
              "gloas - minimal - sanity/blocks - invalid_too_many_payload_attestations",
              "gloas - minimal - sanity/blocks - invalid_old_style_deposit_rejected",
              "gloas - minimal - sanity/blocks - invalid_too_many_bls_to_execution_changes",
              "gloas - minimal - sanity/blocks - invalid_too_many_voluntary_exits",
              "gloas - minimal - sanity/blocks - invalid_too_many_attester_slashings",
              "gloas - minimal - sanity/blocks - invalid_too_many_attestations"));

  private final Set<String> fixtures;

  SszMaxLengthFixtures(final Set<String> fixtures) {
    this.fixtures = fixtures;
  }

  public void run(final TestDefinition testDefinition, final TestExecutor executor)
      throws Throwable {
    if (!fixtures.contains(key(testDefinition))) {
      executor.runTest(testDefinition);
      return;
    }
    try {
      executor.runTest(testDefinition);
    } catch (final SszMaxLengthExceededException expected) {
      return;
    }
    throw new AssertionError(
        testDefinition
            + " is no longer rejected by an SSZ limit, remove it from "
            + getClass().getSimpleName());
  }

  private static String key(final TestDefinition testDefinition) {
    return testDefinition.getDisplayName();
  }
}
